name: dotnet-pull-request
on:
  workflow_call:
    inputs:
      dotnet-version:
        required: false
        type: string
        default: '10.0.x'
permissions:
  contents: read
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Novolis-Platform/novolis-workflows/actions/setup-dotnet@main
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
      - uses: Novolis-Platform/novolis-workflows/actions/authenticate-github-packages@main
      - uses: Novolis-Platform/novolis-workflows/actions/restore@main
      - uses: Novolis-Platform/novolis-workflows/actions/build@main
      - uses: Novolis-Platform/novolis-workflows/actions/test@main
