name: dotnet-raylib-merge-publish
on:
  workflow_call:
    inputs:
      dotnet-version:
        required: false
        type: string
        default: '10.0.x'
      skip_publish:
        required: false
        type: boolean
        default: false
permissions:
  contents: write
  packages: write
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Novolis-Platform/novolis-workflows/actions/raylib-build-test@main
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - uses: Novolis-Platform/novolis-workflows/actions/raylib-pack-publish@main
        id: publish
        if: inputs.skip_publish == false

      - uses: Novolis-Platform/novolis-workflows/actions/commit-version-bump@main
        if: inputs.skip_publish == false
        with:
          next_version: ${{ steps.publish.outputs.next_version }}
