name: dotnet-raylib-pull-request
on:
  workflow_call:
    inputs:
      dotnet-version:
        required: false
        type: string
        default: '10.0.x'
permissions:
  contents: read
  packages: read
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Novolis-Platform/novolis-workflows/actions/raylib-build-test@main
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
